### ISSUE TITLE
lab2 review 

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/volkov-alexandr#11]
Переделайте те задачи, что помечены в issues. Основная ошибка - неиспользвание или неправильное испольование функций (одна и та же функция может быть использована несолько раз). Нет задач 2, 3, 7, 13 - даже если они слишком легкие или вы уже их показали преподавателю на паре, они должны быть в репозитории иначе не будут оценены.

**Comment by Volalex2000** [comment]
Задачи 2,3,7,13 добавлены в репозиторий
