### ISSUE TITLE
lab3_2/gravitational_force.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-927/volkov-alexandr#14]
1) Нужно лучше отструктурировать программу, создать функцию main, в которой уже выполняются остальные функции. 
2) Не рекомендуется использование `global`, лучше таскать переменные типа координата и скорость через параметры. Если тебе не нравится, что тогда у функции будет слишком много параметров, храни векторы в массивах а ля `x=[1.2,0.5,1.9]` и передовай в аргумент сразу массив. Можешь также почитать про библиотеку numpy, с помощю нее можно складывать массивы (и вообще делать любые алгебраические операции) не поэлементно, а как целое.
То же самое про окно, его лучше тоже таскать везде как аргумент функции (а вдруг у тебя будут ещё окна?).
3) PEP8: определения функций отделяются двумя пустыми строками.

**Comment by Volalex2000** [comment]
Все исправлено
